# Generated by Django 4.1.2 on 2022-10-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_filmwork_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.TextField(choices=[('male', 'male'), ('female', 'female')], max_length=6, null=True, verbose_name='gender'),
        ),
    ]
