# Generated by Django 4.1.2 on 2022-10-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_person_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='file_path',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='movies/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.TextField(choices=[('male', 'Male'), ('female', 'Female')], max_length=7, null=True, verbose_name='Gender'),
        ),
    ]
