# Generated by Django 4.1.2 on 2022-10-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_filmwork_file_path_alter_person_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='file_path',
            field=models.FileField(blank=True, max_length=124, null=True, upload_to='movies/', verbose_name='File'),
        ),
    ]
